version: '2'

services:
  legal-rep-frontend:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: docker.artifactory.reform.hmcts.net/cmc/legal-rep-frontend
