version: '2.1'

services:
    legal-integration-tests:
      image: docker.artifactory.reform.hmcts.net/cmc/legal-integration-tests:${LEGAL_INTEGRATION_TESTS_VERSION:-latest}
      command: test --grep '@legal($$| )'
      environment:
        - WEB_DRIVER_HOST=remote-webdriver
        - LEGAL_APP_URL=${TEST_URL}/legal
        - http_proxy
        - https_proxy
        - no_proxy=remote-webdriver
        - IDAM_URL
        - CLAIM_STORE_URL
      volumes:
        - ./functional-output:/usr/src/app/output
    remote-webdriver:
      image: docker.artifactory.reform.hmcts.net/selenium/standalone-chrome:3.8.1

