version: '2.1'

services:
    legal-integration-tests:
      image: hmctspublic.azurecr.io/cmc/legal-integration-tests:${LEGAL_INTEGRATION_TESTS_VERSION:-latest}
      command: test:integration --grep @legal
      environment:
        - WEB_DRIVER_HOST=remote-webdriver
        - LEGAL_APP_URL=${TEST_URL}
        - http_proxy=http://proxyout.reform.hmcts.net:8080
        - https_proxy=http://proxyout.reform.hmcts.net:8080
        - no_proxy=remote-webdriver
        - IDAM_URL
        - CLAIM_STORE_URL
        - OAUTH_CLIENT_SECRET
      volumes:
        - ./functional-output:/usr/src/app/output
    remote-webdriver:
      image: selenium/standalone-chrome:3.141.59

