nodejs:
  image: hmctspublic.azurecr.io/cmc/legal-frontend:latest
  applicationPort: 4000
  memoryRequests: 256Mi
  memoryLimits: 512Mi
  cpuLimits: 1
  aadIdentityName: money-claims
  ingressHost: 'moneyclaims-legal.{{ .Values.global.environment }}.platform.hmcts.net'
  environment:
    NODE_ENV: production
    REFORM_TEAM: cmc
    REFORM_SERVICE_NAME: legal-frontend
    UV_THREADPOOL_SIZE: 64
    GA_TRACKING_ID: UA-00000000-0
    SERVICE_SURVEY_URL: http://www.smartsurvey.co.uk/s/not-a-real-legal-service-survey/
    FEEDBACK_SURVEY_URL: http://www.smartsurvey.co.uk/s/not-a-real-legal-service-survey/
    REPORT_PROBLEM_SURVEY_URL: http://www.smartsurvey.co.uk/s/not-a-real-legal-service-survey/

    IDAM_API_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    IDAM_AUTHENTICATION_WEB_URL: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net
    IDAM_S2S_AUTH: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PAY_URL: http://payment-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    FEES_URL: http://fees-register-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CLAIM_STORE_URL: http://cmc-claim-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    DRAFT_STORE_URL: http://draft-store-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal

    # feature toggles should be removed when they are no longer needed
    # add them here if they are to be enabled everywhere
    # there should be no more than 2 or 3 at a time
    FEATURE_DASHBOARD: true
    FEATURE_INVERSION_OF_CONTROL: true
  keyVaults:
    cmc:
      secrets:
        - AppInsightsInstrumentationKey
        - legal-oauth-client-secret
        - cmc-s2s-secret
        - legal-draft-store-primary
        - legal-draft-store-secondary
        - legal-cookie-encryption-key

idam-pr:
  enabled: false
