idam_api_url = "https://idam-api.demo.platform.hmcts.net"
authentication_web_url = "https://idam-web-public.demo.platform.hmcts.net"
fees_api_url = "http://fees-register-api-demo.service.core-compute-demo.internal"
payments_api_url = "http://payment-api-demo.service.core-compute-demo.internal"
feature_certificateOfService = "false"
external_host_name = "www.moneyclaims-legal.demo.platform.hmcts.net"
capacity = "2"
