idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
authentication_web_url = "https://idam.preprod.ccidam.reform.hmcts.net"
fees_api_url = "http://fees-register-api-demo.service.core-compute-demo.internal"
payments_api_url = "http://payment-api-demo.service.core-compute-demo.internal"
feature_dashboard = "true"
feature_certificateOfService = "false"
external_host_name = "www.moneyclaims-legal.demo.platform.hmcts.net"
capacity = "2"
